# action.yml
name: 'Process LaTeX Templagtes'
description: 'Scan the repo and process all templates as requried'
# inputs:
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  # args:
  #   - ${{ inputs.who-to-greet }}