on:
  push:
    branches:
      - master
      - ci-setup*

jobs:
  process_templates:
    runs-on: ubuntu-latest
    name: Process templates and push to Curvenote
    steps:
      - run: echo "action triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: echo "CHANGED_FILES=$(git diff --name-only ${{ github.event.before }}  ${{ github.event.after }})" >> $GITHUB_ENV
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Processing action step
        id: processing
        uses: ./.github/actions/process-templates-action

