on:
  push:
    branches:
      - master
      - ci-setup*

jobs:
  process_templates:
    runs-on: ubuntu-latest
    name: Process templates and push to Curvenote
    steps:
      - run: echo "action triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Processing action step
        id: processing
        uses: ./.github/actions/process-templates-action
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      # step - commit updated repo
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
