on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  process_templates:
    runs-on: ubuntu-latest
    name: Process templates and push to Curvenote
    steps:
      - run: echo "action triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The repository is located at ${{ github.workspace }}"
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.PROD_GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.PROD_GCP_SA_KEY }}
          export_default_credentials: true
      - name: Processing action step
        id: processing
        uses: ./.github/actions/process-templates-action
        env:
          GCP_PROJECT_ID: ${{ secrets.PROD_GCP_PROJECT_ID }}
          GCP_SA_KEY: ${{ secrets.PROD_GCP_SA_KEY }}
          BUCKET_NAME: ${{ secrets.PROD_BUCKET_NAME }}
